name: update image when upstream is updats

on:
  push:
    branches: 
      - flan
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-update: ${{ steps.check.outputs.needs-update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.SECRET_TOKEN }}

      - name: Check if update available
        id: check
        uses: mkumatag/container-image-updater-action@v1.0.5
        with:
          base-image: library/python:3.9-alpine
          image: ghcr.io/ayushi-gupta2001/testing-branch/flan-scan:latest
          image-reg-username: ${{ github.actor }}
          image-reg-password: ${{ secrets.SECRET_TOKEN }}

      - name: check if there is any update
        run: echo "${{steps.check.outputs.needs-update}}"
  
  update:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.needs-update == 'true'
    steps: 
      - run: echo "Need to update ${{needs.check.outputs.needs-update}}"
      - name: Checkout repositry
        uses: actions/checkout@v3
 
      - name: pull updated base image and check
        run: docker pull python:3.9-alpine
      
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Reuild the Docker image
        run: 
          docker build . --tag ghcr.io/ayushi-gupta2001/testing-branch/flan-scan:latest

      - name: Check if container is working with rebuild image
        id: conatinerstatus
        run: | 
            containerId=$(docker run --rm -it -d  ghcr.io/ayushi-gupta2001/testing-branch/flan-scan:latest)
            sleep 60

            containerStatus=$(docker inspect --format="{{ .State.Status }}" $containerId)

            if [ "$containerStatus" == "running" ]; then
              echo "container is working!!"
            else
              echo "container is not starting after 1 minute!,Skipping subsequent steps"
              exit 1
            fi

      - name: Publish new docker image
        run: docker push  ghcr.io/ayushi-gupta2001/testing-branch/flan-scan:latest


  no_update_value:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.needs-update == 'false'
    steps: 
      - run: echo "No need to update ${{needs.check.outputs.needs-update}}"
      