name: Auto build images when upstream is updated or not

on:
  push:
    branches: 
      - auto-update

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: ubuntu:22.04
          image: testing-branch/auto-update:latest

      - name: pull base image
        if: steps.check.outputs.needs-updating == 'true'
        run: | 
            docker pull node:18-alpine

      - name : Reuild docker image with new base image
        run: |
          if [ "${{ steps.check.outputs.needs-updating}}" == "true" ]; then
            docker build -t testing-branch/auto-update:latest .
          fi

      - name: Publish the docker image
        env:
            TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
            if [ "${{ steps.check.outputs.needs-updating }}" == "true" ]; then
              echo $TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
              [[ "$GITHUB_REF_NAME" == "master" ]] && export TAG="latest" || TAG="$GITHUB_REF_NAME"
              docker push ghcr.io/testing-branch/auto-update:latest
            fi
