name: update image when upstream is updats

on:
  push:
    branches: 
      - auto-update
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-update: ${{ steps.check.outputs.needs-update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.SECRET_TOKEN }}

      - name: Check if update available
        id: check
        uses: mkumatag/container-image-updater-action@v1.0.5
        with:
          base-image: library/ubuntu:20.04
          image: ghcr.io/ayushi-gupta2001/testing-branch/auto-update:latest
          image-reg-username: ${{ github.actor }}
          image-reg-password: ${{ secrets.SECRET_TOKEN }}

      - name: check if there is any update
        run: echo "${{steps.check.outputs.needs-update}}"
  
  update:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.needs-update.result == 'true'
    steps: 
      - run: echo "Need to update Image! ${{needs.check.outputs.needs-update.result}}"

  no_update_value:
    runs-on: ubuntu-latest
    needs: check_update
    if: needs.check_update.output.needs-update == 'false'
    steps: 
      - run: echo "No need to update ${{needs.check.outputs.needs-update.result}}"
      