name: update image when upstream is updats

on:
  push:
    branches: 
      - auto-update
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      need_update: ${{ steps.check.outputs.need_update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.SECRET_TOKEN }}

      - name: Check if update available
        id: check
        uses: mkumatag/container-image-updater-action@v1.0.5
        with:
          base-image: library/ubuntu:20.04
          image: ghcr.io/ayushi-gupta2001/testing-branch/auto-update:latest
          image-reg-username: ${{ github.actor }}
          image-reg-password: ${{ secrets.SECRET_TOKEN }}
    
  build:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.need_update == 'true'
    steps:
      - run: echo "Need update"

      # - name: if it is update , notifiy us!!
      #   run: echo need_update ${{steps.check_update.output.need_update }}
      #   if: steps.check_update.output.need_update == 'true'

  # no_update_value:
  #   runs-on: ubuntu-latest
  #   needs: check_update
  #   steps: 
  #     - run: echo No need to update ${{ needs.check_update.output.need_update }}
  #       if: $steps.check_update.output.need_update == 'false'